[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./testdata" },
    { access = "read-write", path = "./result.json" },
]
ffi = true

[rpc_endpoints]
base-sepolia = "https://sepolia.base.org"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }
