[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "." }]

[rpc_endpoints]
base-sepolia = "https://sepolia.base.org"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }
